#!/bin/bash

# Quick Deploy Commands - Copy/Paste These!

echo "═══════════════════════════════════════════════════════"
echo "   NOOCARB - QUICK DEPLOY COMMANDS"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Choose your preferred method and copy the commands:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟢 METHOD 1: Deploy Script (Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd /workspace && ./deploy.sh"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 METHOD 2: Vercel CLI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "npm install -g vercel"
echo "cd /workspace"
echo "vercel"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔵 METHOD 3: Netlify CLI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "npm install -g netlify-cli"
echo "cd /workspace"
echo "netlify deploy --prod"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 METHOD 4: Test Locally First"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd /workspace"
echo "npm run preview"
echo "# Then open: http://localhost:4173"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🌐 METHOD 5: No CLI - Drag & Drop"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Vercel: https://vercel.com"
echo "   1. Sign up/Login"
echo "   2. Drag /workspace folder"
echo "   3. Get URL!"
echo ""
echo "Netlify Drop: https://app.netlify.com/drop"
echo "   1. Drag /workspace/dist folder"
echo "   2. Get URL instantly!"
echo ""

echo "═══════════════════════════════════════════════════════"
echo ""
echo "💡 TIP: Use Method 1 (./deploy.sh) for easiest deploy!"
echo ""
echo "📚 For detailed help, read:"
echo "   - 🚀-START-HERE.txt"
echo "   - START_HERE.md"
echo "   - DEPLOYMENT.md"
echo ""
echo "═══════════════════════════════════════════════════════"
